# fly.toml app configuration file generated for apolloserver-lingering-fire-9029-black-snow-6986-holy-glade-3046-snowy-morning-2163 on 2024-01-29T20:33:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apolloserver-lingering-fire-9029-black-snow-6986-holy-glade-3046-snowy-morning-2163'
primary_region = 'waw'

[build]
  image = 'node:14'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0

[[services.ports]]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
